version: '3.8'
services:
  frontend:
    build: client
    ports:  
     - 8080:8080
  backend:
    build: server
    environment: 
      - MONGO_URI = "mongodb+srv://admin:12345@todoapp.4wcql.mongodb.net/todo?retryWrites=true&w=majority"
      - PORT = 3000
    ports: 
     - 3000:3000
  mongodb:
    image: mongo:4.2