name: publish

on: [push]

jobs:
  build:
    name: Cloud Run Deployment
    runs-on: ubuntu-latest
    steps:

      - name: Checkout
        uses: actions/checkout@master

      - name: Setup GCP Service Account
        uses: GoogleCloudPlatform/github-actions/setup-gcloud@master
        with:
          version: 'latest'
          service_account_email: ${{ secrets.GKE_SA_EMAIL }}
          service_account_key: ${{ secrets.GKE_SA_KEY }}
          export_default_credentials: true

      - name: Deploy
        run: |
          gcloud run deploy client \
          --region europe-west1 \
          --image gcr.io/${{ secrets.GCP_PROJECT_ID }}/client \
          --memory=1Gi \
          --platform managed \
          --allow-unauthenticated \
          --project ${{ secrets.GCP_PROJECT_ID }}
          
          gcloud run deploy server \
          --region europe-west1 \
          --image gcr.io/${{ secrets.GCP_PROJECT_ID }}/server \
          --platform managed \
          --allow-unauthenticated \
          --project ${{ secrets.GCP_PROJECT_ID }}
